name: E.T_phone_home
on:
  push:
    branches: ["master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Fetch Git tags for incremental versioning
        run: git fetch --tags

      - name: Tag version
        id: version
        uses: bitshifted/git-auto-semver@v1
        with:
          main_branch: ${{ github.ref_name }}
          create_tag: true
          tag_prefix: ${{ github.ref_name == 'dev' && 'dev' || 'master' }}

      - name: JAR versioning
        run: |
          sed -i "s/1.0.0/${{ steps.version.outputs.version-string }}/g" build.gradle.kts



      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: matankaufman/helloworld:${{ steps.version.outputs.version-string }}

      - name: PUll and Run from Dockerhub
        run: |
         docker pull matankaufman/helloworld:${{ steps.version.outputs.version-string }}
         docker run  --name E.T_PHONE_HOME matankaufman/helloworld:${{ steps.version.outputs.version-string }}
